name: Lint

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest

        strategy:
            matrix:
                NODE_VERSION: [20.x]

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.NODE_VERSION }}

            - name: Code Checkout
              uses: actions/checkout@v3

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache Node.js modules
              id: yarn-cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install Dependencies
              run: yarn install --frozen-lockfile --silent
              env:
                  CI: true

            - name: Build the project
              run: yarn build

            - name: Lint the project with Yarn
              run: yarn lint
